server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    server_name localhost;

    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;

    location / {
        try_files $uri /index.html;
    }
}
