spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5434/dainf_lab}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:5432}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect